### ISSUE TITLE
maven central

### ISSUE THREAD

**Issue by Sammers21** [petersamokhin/vk-bot-java-sdk#1]
Better to have your library in maven central

**Comment by petersamokhin** [comment]
Yes, I wrote that the library now at the pre-alfa stage and need to be debugged. In one-two days I would make big update (Callback API support, small fixes, etc). I think, In one-two weeks after testing and debugging, I will upload library to the maven central.
You can help to project with testing of it.
Thanks.

**Comment by petersamokhin** [comment]
Have already uploaded this library to the maven central repository. It will be available in one-two hours. Thanks!

**Comment by petersamokhin** [comment]
Have already uploaded this library to the maven central repository. It will be available in one-two hours. Thanks!
