### ISSUE TITLE
Слишком детальный вывод в лог для уровня INFO

### ISSUE THREAD

**Issue by ghost** [petersamokhin/vk-bot-java-sdk#12]
Недавно начал использовать эту библиотеку в своем проекте, но столкнулся с проблемой излишней детализированности логов - то, что как правило скрывают под DEBUG/TRACE, оказалось на уровне INFO, и сообщения от моего приложения теряются среди сообщений этой библиотеки.

Я не очень знаком с Log4j, использовал для ведения логов библиотеку logback. Есть ли возможность поменять уровень выводимых в лог сообщений?

**Comment by Plasticable** [comment]
Да, в Log4J можно задать уровень логирования для пакетов.
`<Logger name="com.petersamokhin.bots.sdk" level="WARN"/>`

**Comment by ghost** [comment]
Спасибо, теперь работает как нужно.
