### ISSUE TITLE
Ответ с ошибкой #2 от сервера Longpoll

### ISSUE THREAD

**Issue by ghost** [petersamokhin/vk-bot-java-sdk#14]
В ходе работы бот сообщений для паблика ВК пускает в лог такие сообщения:

```
[threadLongpollListener/ERROR] [com.petersamokhin.bots.sdk.longpoll.LongPoll] Response of VK LongPoll fallen with error code 2
```

В документации к Vk Bot Long Poll API указано, что ошибка #&#x2060;2 означает, что "истекло время действия ключа".
Также заметил, что бот либо игнорирует эту ошибку и дальше получает события, либо действительно получает ключ заново. В таком случае, вывод этой ошибки в лог следует заглушить.

**Comment by petersamokhin** [comment]
@scpketer привет! Библиотека не поддерживалась более двух лет, и я вообще не уверен, находится ли эта старая версия в работоспособном состоянии. 
Теперь я выпустил новую версию библиотеки, переписанную с нуля.
