### ISSUE TITLE
Клавиатура

### ISSUE THREAD

**Issue by kovalchuk11** [petersamokhin/vk-bot-java-sdk#15]
Можно ли вставить клавиатуру в сообщение используя эту библиотеку?

**Comment by kosheeta** [comment]
У меня тот же вопрос!

**Comment by petersamokhin** [comment]
@kovalchuk11 @ItzNeviKat ранее, в старой версии, было нельзя: библиотека не поддерживалась более двух лет и я не могу гарантировать работоспособность старой версии. 
Сейчас я выпустил новую версию библиотеки, в ней работа с клавиатурой полностью поддерживается.
