### ISSUE TITLE
Получаю null при обращение к IncomingMessage#getRefSource()

### ISSUE THREAD

**Issue by callmesensey** [petersamokhin/vk-bot-java-sdk#16]
```Java
        client.onMessage(event -> {
                Bootstrap.getConfig().getStringList("configuration.admins").forEach(adminId -> new Message()
                        .peerId(adminId)
                        .text("Новое сообщение от @" + event.getMessage().getRefSource())
                        .sendFrom(client)
                        .execute());
            }
        });
```

**Получаемое сообщение:** Новый тикет от @null

**Вопрос:** Это ошибка в SDK или я не правильно использую метод getRefSource?

**Comment by petersamokhin** [comment]
@DokanBoy согласно документации VK, refSource это реферальные ссылки при переходе в диалог со стороннего сайта. Если нужно сделать упоминание юзера, надо делать что-то вроде “@id” + message.getUserId()

**Comment by callmesensey** [comment]
Сорри, спасибо
