### ISSUE TITLE
Не работает java пример из readme.md, client.startLongPolling() выдает ошибку.

### ISSUE THREAD

**Issue by Egorrko** [petersamokhin/vk-bot-java-sdk#17]
при выполнении client.startLongPolling() он перехватывает ошибку `BotsLongPollApi::exceptionHandler::error = com.petersamokhin.vksdk.core.error.VkResponseException: BotsLongPollApi initiation error: bad VK response: Error occurred during the VK response`
В настройках группы Long Poll API включен, версия стоит 5.103, в коде версию не указывал.
Пробовал менять и в коде  `new VkSettings(vkHttpClient, 5.107)` и в группе на 5.107, 5.50.
Как можно узнать что конкретно за ошибку возвращает вк? Может я что-то делаю не так?

**Comment by petersamokhin** [comment]
Привет. Узнать точнее, что за ошибку возвращает VK можно, например, включив логгинг у `HttpClient`-a. Покажи свой код, где ты инициализируешь HttpClient и VkApiClient, я попробую подсказать.

**Comment by Egorrko** [comment]
https://pastebin.com/fn05uV4Z
Это весь код, что у меня есть. Токен скинул в личку группы вк.

**Comment by petersamokhin** [comment]
> Токен скинул в личку группы вк.

Зря, он не нужен.

Вижу, используется OkHttp. Тогда можно взять это: https://github.com/square/okhttp/tree/master/okhttp-logging-interceptor

И сделать как-то так:
```java
HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
logging.setLevel(Level.BODY);

OkHttpClient okHttpClient = new OkHttpClient.Builder()
  .addInterceptor(logging)
  .build();
```

И потом уже в твоем коде:
```java
HttpClient vkHttpClient = new VkOkHttpClient(okHttpClient);
```

Так в логах ты увидишь ответ от сервера VK и поймешь, в чем проблема.
