### ISSUE TITLE
Не отправляется клавиатура.

### ISSUE THREAD

**Issue by NikitaBolshakov** [petersamokhin/vk-bot-java-sdk#21]
![Screenshot from 2020-09-07 09-03-39](https://user-images.githubusercontent.com/58260141/92353665-85240d00-f0e9-11ea-944c-cdb4e84a8454.png)
![Screenshot from 2020-09-07 09-03-45](https://user-images.githubusercontent.com/58260141/92353660-82c1b300-f0e9-11ea-8b66-57bd4e202501.png)

**Comment by petersamokhin** [comment]
@NikitaBolshakov настройки для ботов в группе все установлены? Версия вк API правильная, и тд? Могу посоветовать попробовать не `oneTime`.

**Comment by NikitaBolshakov** [comment]
Попробовал, все еще не работает. Может быть здесь что-то не так?
![Screenshot from 2020-09-08 10-12-49](https://user-images.githubusercontent.com/58260141/92445323-e10b9600-f1bc-11ea-8bc5-bd0a8a208b4b.png)
![Screenshot from 2020-09-08 10-13-12](https://user-images.githubusercontent.com/58260141/92445342-e7017700-f1bc-11ea-8000-d1ed86136430.png)
![Screenshot from 2020-09-08 10-14-58](https://user-images.githubusercontent.com/58260141/92445350-e9fc6780-f1bc-11ea-9234-3b4624bea2c9.png)

**Comment by petersamokhin** [comment]
@NikitaBolshakov как минимум требуется указать таймауты, чтобы соединение не обрывалось:
https://vksdk.github.io/vk-sdk-kotlin/http-clients/#abstract-http-client-configuration
^ для OkHttp-based клиента этого будет достаточно. Дальше можно еще что-то будет пробовать. Возможно, здесь просто соединение обрывалось и бот вообще не реагировал поэтому

**Comment by NikitaBolshakov** [comment]
Да вот дело в том, что сообщение без клавиатуры отправляется. Поэтому я, собственно, и написал про клавиатуры

**Comment by callmesensey** [comment]
А @NikitaBolshakov "Возможности ботов" включены? 
![image](https://user-images.githubusercontent.com/24508965/92866056-46fc5580-f429-11ea-957e-b589f0e09863.png)

**Comment by NikitaBolshakov** [comment]
Да, включены)

**Comment by petersamokhin** [comment]
Только что проверил собственноручно, все работает, проблема точно не в библиотеке ¯\\\_(ツ)\_/¯ 

Вот пример:
```kotlin
client.sendMessage {
    peerId = 62802565
    message = "Test"
    keyboard = keyboard {
        row {
            primaryButton("Blue pill")
            negativeButton("Red pill")
        }
    }
}.execute()
```

«Возможности для ботов» включены, версия Long Poll API должна быть не ниже 5.103, и остальные базовые настройки — больше ничего не требуется.
