### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by nutrolshok** [petersamokhin/vk-bot-java-sdk#27]
Ошибка такая же, как и тут https://github.com/vksdk/vk-sdk-kotlin/issues/17
Подробные логи: 
![Screenshot_546](https://user-images.githubusercontent.com/47331021/99913939-75d95680-2d0b-11eb-80c8-0380169d82a6.png)
![Screenshot_547](https://user-images.githubusercontent.com/47331021/99913940-77a31a00-2d0b-11eb-9f84-945b261a4b31.png)

**Comment by petersamokhin** [comment]
> longpoll for this group is not enabled

Ошибка не относится к библиотеке.
