### ISSUE TITLE
Не собирается из-за отсутствия классов 

### ISSUE THREAD

**Issue by kolokolovg** [petersamokhin/vk-bot-java-sdk#3]
com.petersamokhin.bots.sdk.callbacks.callbackapi.* классов нет в проекте

**Comment by petersamokhin** [comment]
В новом фиксе для библиотеки я убрал то безобразие, которое оставил на потом. Вместо нескольких десятков коллбэков, используется один единственный с дженериком.

Документация, к сожалению, не соответствует текущей версии библиотеки, она очень устарела.

**Comment by petersamokhin** [comment]
К сожалению, на данный момент было добавлено не так много нововведений и фиксов, чтобы выкатывать новую версию в центральный репозиторий, но достаточно для того, чтобы библиотека была в отличном работоспособном состоянии. 

Советую склонить проект с гита и использовать напрямую, в случае необходимости делая свои правки. В текущем варианте на гите, библиотека не имеет найденных багов/ошибок и работает более, чем стабильно (не один, не два и не десять ботов давно на ней висят).

Спасибо!

**Comment by kolokolovg** [comment]
Так я и пишу про версию с гитхаба, она не собирается.
В мавен-централе собранная либа содержит необходимые классы.
В гихабе их нет.

**Comment by petersamokhin** [comment]
Какая именно ошибка появляется, на вызове какого метода библиотеки?

Да, сейчас заметил, секунду, подправлю :)
Забыл, что не везде исправил.

На самом деле, коллбэк апи в библиотеке, пока что, это один большой баг, и использовать это нужно с осторожностью: во-первых, этот раздел практически не тестировался, и во-вторых, используется не самый крутой фреймворк (spark java), который в скором времени будет заменён на spring mini, и, возможно, вся библиотека будет переписана на котлине (совместимость с Java гарантируется 100%-ная).

**Comment by kolokolovg** [comment]
Сама библиотека не собирается с исходников с гитхаба.
В классе src/main/java/com/petersamokhin/bots/sdk/utils/vkapi/CallbackApiHandler.java
ссылки на несуществующие в проекте классы
OnBoardPostEditCallback и так далее

**Comment by petersamokhin** [comment]
Исправлено, только что убрал эту ошибку и запушил. 

Изменён был только `CallbackApiHandler` класс, можете заново склонить с гита, или же изменить только этот класс.

**Comment by kolokolovg** [comment]
Еще потерянные классы в Message

vk-bot-java-sdk/src/main/java/com/petersamokhin/bots/sdk/objects/Message.java:[3,56] package com.petersamokhin.bots.sdk.callbacks.callbackapi does not exist

**Comment by petersamokhin** [comment]
Спасибо большое, это тоже подправил: когда убирал кучу коллбэков, забыл, где их использовал.

Обновил класс `Message`, ошибка исправлена.

Больше таких ошибок быть не должно.
