### ISSUE TITLE
Проблема с аутентификацией

### ISSUE THREAD

**Issue by ghost** [petersamokhin/vk-bot-java-sdk#4]
Добрый день, возникает проблема с аутентификацией.
Запуск... https://hastebin.com/onotuxazas.java
Ошибку выбивает примерно через 15 секунд после запуска
Ошибка... https://hastebin.com/hitajopuno.bash

**Comment by petersamokhin** [comment]
Я бы попросил вас настроить log4j логгер, ибо все ошибки выводятся на `ERROR` уровне через него. Без нормального описания ошибки я помочь вам не смогу: на данный момент не ясно, проблема в моём обработчике (что вряд ли), либо в ответе от самих ВК.

**Comment by ghost** [comment]
Прошу прощения, моя вина с "неисправностью". С вашим обработчиком проблем нет (забыл включить VPN так как я из Украины).
